I4VGen:
  inference_config: "configs/animatediff_configs/inference/inference-v2.yaml"
  motion_module:
    - "/home/jhpark/AnimateDiff/models/Motion_Module/v3_sd15_mm.ckpt"
  PIA_path: "/home/jhpark/PIA/models/PIA/pia.ckpt"

  controlnet_image: "/home/jhpark/ImageDataset/0.png"
  dreambooth_path: "/home/jhpark/AnimateDiff/models/DreamBooth_LoRA/rcnzCartoon3d_v10.safetensors"
  controlnet_path: "/home/jhpark/AnimateDiff/models/SparseCtrl/v3_sd15_sparsectrl_rgb.ckpt"
  controlnet_config: "configs/sparsectrl/latent_condition.yaml"
  controlnet_image_index: [0]
  use_fp16: true

  seed:           [3521461,1268,12538]
  steps:          25
  guidance_scale: 7.5

  L: 16
  H: 512
  W: 512

  prompt:
    - "a girl is smiling"
    - "a girl is raising one hand"
    - "a girl is crying"

  n_prompt:
    - ""